# db_utils.py
from sqlmodel import Session, SQLModel
from typing import List
from models.hero import Hero  # Ensure to import your Hero model and engine
from db import engine  # Your SQLModel engine setup
from sqlalchemy import text

# def insert_single_hero(hero: Hero) -> Hero:
#     """
#     Inserts a single Hero record into the database.
#     Returns the inserted Hero with its generated ID.
#     """
#     with Session(engine) as session:
#         session.add(hero)
#         session.commit()
#         session.refresh(hero)
#         return hero


def insert_multiple_heroes(heroes: List[Hero]) -> List[Hero]:
    """
    Inserts multiple Hero records at once.
    Returns the list of inserted Hero objects (with IDs populated).
    """
    with Session(engine) as session:
        for h in heroes:
            session.add(h)
        session.commit()
        # Refresh each hero to load autogenerated fields like ID
        for h in heroes:
            session.refresh(h)
        return heroes


def insert_single_hero(table_name: str, data: dict) -> dict:
    """
    Inserts a single record into the specified table using raw SQL.
    Returns the inserted data on success.
    """
    columns = ", ".join(data.keys())
    placeholders = ", ".join(f":{col}" for col in data.keys())

    # print(f"Inserting into {table_name} with columns: {_columns} and placeholders: {_placeholders}")
    stmt = text(f"INSERT INTO {table_name} ({columns}) VALUES ({placeholders})")
    print(f"SQL Statement: {stmt}")

    with Session(engine) as session:
        session.execute(stmt, data)
        session.commit()

    return data
